
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.0.46",
    version: "0.0.46 (c91b8bbf85fb09c686c177ad10787ec2)",
    buildSeed: 1611724252068,
};
