
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.0.48",
    version: "0.0.48 (6448408f9b5b88562144e9291bb7c0b3)",
    buildSeed: 1611807191223,
};
