
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.0.47",
    version: "0.0.47 (a10d436df0a7cc3c260496562adb7a6f)",
    buildSeed: 1611743111407,
};
